name: integration

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

permissions:
  contents: read
  pull-requests: read

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Make directory for application-test.yml
        run: mkdir -p ./src/test/resources

      - name: Make application-test.yml
        run: touch ./src/test/resources/application-test.yml

      - name: Write application-test.yml
        run: echo "${{ secrets.APPLICATION_TEST_YML }}" > ./src/test/resources/application-test.yml

      - name: Setup Java JDK 17 Adopt
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: gradlew build # build task에 test 포함
        run: ./gradlew build 
